:PROPERTIES:
:ID:       4fc0d3fb-f7fe-45d7-bfbb-67a3037610d8
:END:
#+title: Testing

* Лекция 01.02.2025

Его основная цель оценить текущее или финальное качество прокта и принять соответствующие
решение и меры.

Отчеты о результатах тестирование - это часть тестовой документации включающая в себя
описание процесса тестирования информацию о деятельности тестировщиков а также некоторые статистические данные

Структура отчета о результатах тестирования:
1) Команда тестировщиков
2) Описание процесса тестирования
3) Краткое описание
4) Расписание
5) Рекомендации
6) Статистика по ошибкам
7) Статистика новых ошибок
8) Статистика по всем ошибкам

** Модульное тестирование
Модульное  тестирование - это тип тестирование ПО при котором тестироются отдельные модули или компоненты ПО

** Интеграционное тестирование
Это тип тестирование при котором программные модули объединяются логически и тестируются как группа.
Методы:
- Восходящее тестирование (сначала тестироются все модули, и только затем они объединяются для интеграционного тестирования)
- Монолитнок тестирование (отдельные компоненты системы серьёзного тестирования не проходили)
- Нисходящее тестирование (предпологает что процесс интеграционного тестирования движется следом за разработкой, сначала т
  тестироются самый верхний уровень системы без модулей низкого уровня, а затем постепенно с более высокоуровневыми модулями интегрируются более)
Основное недостаток: необходимость использования заглушек  
Алгоритм интеграционного тестирования:
1) Подготовка плана интеграционного тестов
2) Разработка тестовых сценариев
3) Выполнение тестовых сценариев и фиксирование багов
4) Отслеживание дефектов и тестирование
5) Повторение 3 и 4 этапов до успешного завершения интеграции

** Системное тестирование
Это тестирование ПО выполняемой на полной интеграционной системе с целью проверки соответствия системы
исходным требованиям как функциональным так и не функциональным. Оно выполняется методом черного ящика
Выделяют 2 подхода к системному тестированию на базе требований. Тестирование проводится в соответствии с функциональным или нефункциональными
требованиями для каждого из которых проводится тест-кейс.

На базе случаев использования. Тестирование происходит в соответствии с вариантами использования продукта на основе которых создаются
user-case







